[ABC-003] AutoMapper, UnitTests
DevKP/WebApiProject pull request #3
Opened 2022-03-18 14:14 UTC by DevKP

+ AutoMapper and products service
+ Serilog

+ Unit tests for products service
+ Move to async methods

+ Exception handling

2022-03-18 17:13 UTC, demchuknick6 requested changes

2022-03-18 17:13 UTC, demchuknick6 commented on WebApiProject/Program.cs
> +                .CreateLogger();
can be moved to a separate method

2022-03-18 17:13 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +        private readonly ILogger<ProductsService> _logger;
i guess it is better to have `ILogger<IProductsService>`

2022-03-18 17:13 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +            _logger = logger;
a great thing would be to add Guard clauses - https://stavroskasidis.com/blog/2017/tips-and-tricks-1-guard-clauses/
and then use them like this: 
`GuardClauses.IsNotNull(_productsRepository ,nameof(_productsRepository));`
also, then you can add unit tests: `Ctor_throws_argument_null_expeption_if_productsRepository_is_null`
same for each Ctor parameter

2022-03-18 17:13 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                _logger.LogError("Error while retrieving product {Id} from database.", id);
you definitely should log the `ex.Message` because have to know what kind of error happens and how to fix it if exception is thrown

2022-03-18 17:13 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                    ErrorMessage = ex.Message,
for the user, `Error while retrieving product from database.` is a good error message, not the technical details of your code that `ex.Message` contains..

2022-03-18 17:13 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                var response = new Response<ProductResponseModel[]>
why don't you use productListResponseModel then?

2022-03-18 17:21 UTC, DevKP commented on WebApiProject.Infrastructure/Configurations/ProductConfiguration.cs
>              builder.Property(product => product.IsAvailable).IsRequired();
This constrain was in the first migration by default, so in fact there are no changes..

2022-03-19 14:20 UTC, DevKP commented on WebApiProject/Services/ProductsService.cs
> +            _logger = logger;
@demchuknick6 In which layer is it better to place guard clauses?(Which project)

2022-03-21 18:52 UTC, demchuknick6 reviewed
good job, but some comments still should be fixed. 
also, I don't see tests for ProductRepository

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        {
whenProductExists_thenReturnOkProductResponse. it's better to add verbs in when and then parts of the test name for better understanding.

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        {
also, you should avoid `async void`. Only use `async void` for event handlers. use `async Task`

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        {
ThenReturnNotFoundResponse

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        {
also, comments for arrange, act, assert can be removed, one empty line between such code blocks is enough

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject/Controllers/ProductsController.cs
> +                _ => StatusCode(500)
please fix my comment above

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject/Program.cs
> +            {
catch block can be added to write log errors when the host builder couldn't be built and run.

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +            try
add before `try` block: `var response = new Response<ProductResponseModel>()`

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                }
```
if (responseModel == null)
{ 
    response.Status = ResponseStatus.NotFound;
    response.ErrorMessage = ErrorMessages.NotFoundInDatabase;
 }
else
{
    response.Data = responseModel;
    response.Status = ResponseStatus.Ok
}
```

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                };
```
response.Status = ResponseStatus.Error;
response.ErrorMessage = ErrorMessages.ErrorWhileRetrievingEntity
```

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                };
and `return response;`after catch block

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                };
same here, create a `response` variable only once before try-catch, and return it as a method result afterward.

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        private readonly ProductsService _productsService;
please rename `_productsService` to `sut` (system under test) - so it's more clear what exactly is tested here

2022-03-21 18:52 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        }
not quite sure why do we need this code..

2022-03-21 19:13 UTC, DevKP commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        }
Without "OmitOnRecursionBehavior" it cannot create entity due to recursion inside the model

2022-03-21 19:21 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        }
then it's better to investigate and fix this recursion,

2022-03-23 10:48 UTC, demchuknick6 commented on WebApiProject.Infrastructure/Repositories/ProductsRepository.cs
>  using System.Text;
do you really need reflection?

2022-03-23 10:48 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsRepositoryTests.cs
> +        {
where T: IEntity

2022-03-23 10:48 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsRepositoryTests.cs
> +        private readonly Fixture _fixture = new();
initialize in constructor

2022-03-23 10:48 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        private readonly Fixture _fixture = new();
init in ctor

2022-03-23 10:48 UTC, demchuknick6 commented on WebApiProject.UnitTests/ProductsRepositoryTests.cs
> +        private readonly Fixture _fixture = new();
also, is it possible to add guard clause to repo to check dbcontext not null and add a unit test accorindly?

2022-03-23 10:48 UTC, demchuknick6 commented on WebApiProject/Services/ProductsService.cs
> +                    _logger.LogInformation("Products list is empty.");
not sure it 's really correct to return 404 when repository returns no results. empty list is also a result,  at least it is not null. but if you want to build your business logic in such way - ok, leave it as it is

2022-03-23 10:48 UTC, demchuknick6 commented on WebApiProject/WebApiProject.Web.csproj
> +    <PackageReference Include="Ardalis.GuardClauses" Version="4.0.0" />
I expected you to write your own guard clauses class, but this is also okay))

2022-03-23 13:51 UTC, DevKP commented on WebApiProject/Services/ProductsService.cs
> +                    _logger.LogInformation("Products list is empty.");
Resolved

2022-03-23 13:51 UTC, DevKP commented on WebApiProject.UnitTests/ProductsServiceTests.cs
> +        private readonly Fixture _fixture = new();
Resolved

2022-03-23 13:51 UTC, DevKP commented on WebApiProject.UnitTests/ProductsRepositoryTests.cs
> +        private readonly Fixture _fixture = new();
Resolved

2022-03-23 13:52 UTC, DevKP commented on WebApiProject.Infrastructure/Repositories/ProductsRepository.cs
>  using System.Text;
Removed unused usings in entire solution

2022-03-23 13:52 UTC, DevKP commented on WebApiProject/WebApiProject.Web.csproj
> +    <PackageReference Include="Ardalis.GuardClauses" Version="4.0.0" />
Sorry.

2022-03-23 14:54 UTC, demchuknick6 commented on WebApiProject.UnitTests/CategoriesRepositoryTests.cs
> +        }
these methods are duplicated, I guess it would be great to create `abstract class DatabaseContextTests`, which would have a `protected readonly DatabaseContext _databaseContext;` field and these methods also as `protected virtual`. then just inherit this class by CategoriesRepositoryTests and ProductsRepositoryTests.

2022-03-23 15:18 UTC, demchuknick6 approved these changes

2022-03-23 15:19 UTC, merged